-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 17:30:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema someDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema someDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `someDB` DEFAULT CHARACTER SET utf8 ;
USE `someDB` ;

-- -----------------------------------------------------
-- Table `someDB`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `someDB`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(45) NOT NULL,
  `CustomerCountry` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `someDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `someDB`.`Orders` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `OrderName` VARCHAR(45) NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `Customer_idCustomer`),
  INDEX `fk_Order_Customer_idx` (`Customer_idCustomer` ASC),
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `someDB`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
